AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BucketName:
    Type: String
    Description:  Bucket Name that stores the malicious IP list
  ObjectName:
    Type: String
    Description:  File Name to store the malicious IP list in S3 Bucket
    Default:  "block_ip_list.txt"

Resources:
  #----------GuardDuty Detector--------------------#
  Detector:
    Type: AWS::GuardDuty::Detector
    Properties:
        Enable: True
        FindingPublishingFrequency: FIFTEEN_MINUTES
  #----------GuardDuty ThreatIntelSet--------------------#
  ThreatIntelIpSet:
    Type: AWS::GuardDuty::ThreatIntelSet
    Properties:
        Activate: true
        DetectorId: !Ref Detector
        Format: "TXT"
        Location: !Join ['',
                    ['https://', !Ref BucketName, '.s3.amazonaws.com/', !Ref ObjectName ]
                  ]
        Name: "MyThreatIntelSet"
